// Code generated by Prismic. DO NOT EDIT.

import Footer from "./Footer/index.svelte";
import Grid from "./Grid/index.svelte";
import Homepage from "./Homepage/index.svelte";
import KeyImage from "./KeyImage/index.svelte";
import PerformerGrid from "./PerformerGrid/index.svelte";
import Hero from "./PerformerHero/index.svelte";
import Slogan from "./Slogan/index.svelte";

export const components = {
	footer: Footer,
	grid: Grid,
	homepage: Homepage,
	key_image: KeyImage,
	performer_grid: PerformerGrid,
	performer_hero: Hero,
	slogan: Slogan
};