// Code generated by Prismic. DO NOT EDIT.

import PerformerGrid from "./PerformerGrid/index.svelte";
import PerformerHero from "./PerformerHero/index.svelte";
import Slogan from "./Slogan/index.svelte";

export const components = {
	performer_grid: PerformerGrid,
	performer_hero: PerformerHero,
	slogan: Slogan
};